package com.system.SchoolManagementSystem.termmanagement.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.system.SchoolManagementSystem.transaction.entity.FeeItem;
import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "term_fee_items",
        indexes = {
                @Index(name = "idx_term_item_student", columnList = "student_term_assignment_id, fee_type"),
                @Index(name = "idx_due_date_status", columnList = "due_date, status"),
                @Index(name = "idx_item_type", columnList = "item_type"),
                @Index(name = "idx_sequence", columnList = "student_term_assignment_id, sequence_order")
        })
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"studentTermAssignment", "feeItemTemplate"})
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Add this
public class TermFeeItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include // Add this
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_term_assignment_id", nullable = false)
    @JsonBackReference
    private StudentTermAssignment studentTermAssignment;

    @Column(name = "item_name", nullable = false, length = 100)
    private String itemName;

    @Enumerated(EnumType.STRING)
    @Column(name = "fee_type", nullable = false)
    private FeeType feeType;

    @Column(name = "item_type", nullable = false, length = 20)
    private String itemType; // BASIC, ADDITIONAL, LATE_FEE, DISCOUNT

    @Column(nullable = false)
    private Double amount;

    @Column(name = "original_amount")
    private Double originalAmount;

    @Column(name = "paid_amount")
    @Builder.Default
    private Double paidAmount = 0.0;

    @Column(name = "pending_amount")
    private Double pendingAmount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private FeeStatus status = FeeStatus.PENDING;

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Column(name = "billing_date", nullable = false)
    private LocalDate billingDate;

    @Column(name = "paid_date")
    private LocalDate paidDate;

    @Column(name = "is_auto_generated", nullable = false)
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "is_mandatory", nullable = false)
    @Builder.Default
    private Boolean isMandatory = true;

    @Column(name = "sequence_order", nullable = false)
    private Integer sequenceOrder;

    // Link to standard FeeItem template if exists
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fee_item_template_id")
    private FeeItem feeItemTemplate;

    @Column(name = "notes", length = 500)
    private String notes;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        billingDate = LocalDate.now();
        if (originalAmount == null) {
            originalAmount = amount;
        }
        calculatePending();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
        calculatePending();
        updateStatus();
    }

    private void calculatePending() {
        this.pendingAmount = Math.max(0, amount - paidAmount);
    }

    private void updateStatus() {
        if (paidAmount >= amount) {
            status = FeeStatus.PAID;
            if (paidDate == null) {
                paidDate = LocalDate.now();
            }
        } else if (paidAmount > 0) {
            status = FeeStatus.PARTIAL;
        } else if (LocalDate.now().isAfter(dueDate)) {
            status = FeeStatus.OVERDUE;
        } else {
            status = FeeStatus.PENDING;
        }
    }

    public void applyPayment(Double paymentAmount) {
        double amountToApply = Math.min(paymentAmount, pendingAmount);
        paidAmount += amountToApply;
        calculatePending();
        updateStatus();

        if (status == FeeStatus.PAID) {
            paidDate = LocalDate.now();
        }
    }

    public Double getRemainingAmount() {
        return pendingAmount;
    }

    public enum FeeType {
        TUITION, BASIC, EXAMINATION, TRANSPORT,
        LIBRARY, SPORTS, ACTIVITY, ADMISSION,
        HOSTEL, UNIFORM, BOOKS, LATE_FEE,
        DISCOUNT, OTHER
    }

    public enum FeeStatus {
        PENDING, PARTIAL, PAID, OVERDUE, WAIVED, CANCELLED, REFUNDED
    }

    public enum ItemType {
        BASIC, ADDITIONAL, LATE_FEE, DISCOUNT, WAIVER, REFUND
    }
}